#!/bin/sh /etc/rc.common
# Freifunk Init
# $Id$

START=99

boot() {
	test -f /etc/crontabs/root || touch /etc/crontabs/root

	[ -d /etc/rc.local.d ] && {
		for file in /etc/rc.local.d/*; do
			test -f "$file" && . "$file"
		done
	}

	/etc/init.d/cron restart &
}
